# Generated by Django 5.1.2 on 2024-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
