# Generated by Django 5.1.2 on 2024-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0005_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
